export const GET_ADDRESSES_REQUEST = 'GET_ADDRESSES_REQUEST'
export const GET_ADDRESSES_SUCCESS = 'GET_ADDRESSES_SUCCESS'
export const GET_ADDRESSES_FAIL = 'GET_ADDRESSES_FAIL'

export const CHANGE_PRIORITY_ADDRESS_REQUEST = 'CHANGE_PRIORITY_ADDRESS_REQUEST'
export const CHANGE_PRIORITY_ADDRESS_SUCCESS = 'CHANGE_PRIORITY_ADDRESS_SUCCESS'
export const CHANGE_PRIORITY_ADDRESS_FAIL = 'CHANGE_PRIORITY_ADDRESS_FAIL'

export const ADD_TO_CART = 'ADD_TO_CART'
export const DELETE_FROM_CART = 'DELETE_FROM_CART'
export const EMPTY_CART = 'EMPTY_CART'
export const UPDATED_CART = "UPDATED_CART"

export const PLACE_ORDER_REQUEST = 'PLACE_ORDER_REQUEST'
export const PLACE_ORDER_SUCCESS = 'PLACE_ORDER_SUCCESS'
export const PLACE_ORDER_FAIL = 'PLACE_ORDER_FAIL'
