export const GET_CUSTOMER_REQUEST = 'GET_CUSTOMER_REQUEST'
export const GET_CUSTOMER_SUCCESS = 'GET_CUSTOMER_SUCCESS'
export const GET_CUSTOMER_FAIL = 'GET_CUSTOMER_FAIL'

export const CHANGE_DEBTOR_REQUEST = 'CHANGE_DEBTOR_REQUEST'
export const CHANGE_DEBTOR_SUCCESS = 'CHANGE_DEBTOR_SUCCESS'
export const CHANGE_DEBTOR_FAIL = 'CHANGE_DEBTOR_FAIL'